# Dependencies
markdown:         kramdown #redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# plugins:  [jekyll-paginate]

# Setup
title:            SIRIUS B
tagline:          "Sharing Inclusive Research Instruction for Underrepresented Students' Benefit"
description:      'Empowerment through enrichment.'
url:              https://github.com/siriusb-org/siriusb-org.github.io #https://siriusb-org.github.io #https://siriusb.org
# baseurl:          / #https://siriusb-org.github.io #/

author:
  name:           'Ava Polzin'
  url:            https://avapolzin.github.io

# paginate:         5

# Custom vars
version:   

github:
  repo:           
